Add Tab Title
face-hh/lyntr pull request #57
Opened 2024-08-06 14:30 UTC by NobreHD

Like the title says it, just adding a title to the tab so it doesn't show a URL
![image](https://github.com/user-attachments/assets/7b3034d6-6e30-4314-9a94-e50fa32b9df8)
to
![image](https://github.com/user-attachments/assets/c1e48254-a953-4a5c-84d8-43e9f84bba9a)

2024-08-06 14:31 UTC, NobreHD commented
Untested code (I don't want to set up everything locally), so please check it before pushing to prod

2024-08-08 01:58 UTC, GStudiosX2 commented
> Like the title says it, just adding a title to the tab so it doesn't show a URL
> ![image](https://github.com/user-attachments/assets/7b3034d6-6e30-4314-9a94-e50fa32b9df8)
> to
> ![image](https://github.com/user-attachments/assets/c1e48254-a953-4a5c-84d8-43e9f84bba9a)

```
/root/projects/lyntr/src/routes/MainPage.svelte:292:0 </svelte:head> attempted to close an element that was not open
/root/projects/lyntr/src/routes/MainPage.svelte:292:0
290 |      {/if}
 291 |    {:else}
 292 |  </svelte:head>
        ^
```

2024-08-08 02:01 UTC, GStudiosX2 requested changes

2024-08-08 02:01 UTC, GStudiosX2 commented on src/routes/MainPage.svelte
> +	{:else}
This should be `{/if}`

2024-08-08 02:01 UTC, GStudiosX2 commented
Ah you fixed it already lol

2024-08-08 02:06 UTC, GStudiosX2 commented
Seems to work if this gets merged I'll have to add it to the messages page too depending which one gets merged first either me or you have to do it

2024-08-09 06:54 UTC, face-hh commented
LGTM

2024-08-09 06:54 UTC, merged